from model import Model

class User(Model):
    def __init__(self):
        super(User, self).__init__()
        self.add_field('id', 'int')
        self.add_field('username', 'str')
        self.add_field('email', 'str')
        self.add_field('first_name', 'str')
        self.add_field('last_name', 'str')
        self.add_field('group_id', 'int')
        self.add_field('manager_of_group_ids', 'list')
        self.add_field('employee_number', 'int')
        self.add_field('salaried', 'bool')
        self.add_field('exempt', 'bool')
        self.add_field('payroll_id', 'str')
        self.add_field('client_url', 'str')
        self.add_field('mobile_number','str')
        self.add_field('hire_date', 'date')
        self.add_field('term_date', 'date')
        self.add_field('last_active', 'datetime')
        self.add_field('active', 'bool')
        self.add_field('require_password_change', 'bool')
        self.add_field('approved_to', 'date')
        self.add_field('submitted_to', 'date')
        self.add_field('last_modified', 'datetime')
        self.add_field('created', 'datetime')
        self.add_field('permissions', 'user_permissions_set')
